# Generated by Django 4.0.3 on 2022-04-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default=None, max_length=800),
        ),
    ]
